### ISSUE TITLE
Release Nette 3.0 compatible version

### ISSUE THREAD

**Issue by JakubBarta** [Kdyby/Events#122]
Hi, 
it seems everything in master is ready for Nette 3.0. If it's really the case, could you please release Nette 3.0 compatible version?

Thanks!

**Comment by enumag** [comment]
It would be better to make Kdyby/Doctrine independent on this package and deprecate Kdyby/Events. See https://github.com/Kdyby/Events/issues/97#issuecomment-301213842.

**Comment by JakubBarta** [comment]
I see.. 
Does it mean the last PR (https://github.com/Kdyby/Events/pull/121) won't be used?
What do you suggest to use instead of this package? https://github.com/contributte/event-dispatcher?

**Comment by enumag** [comment]
Depends on if someone will make the necessary changes for Kdyby/Doctrine. If not then we'll have to stick with Kdyby/Events.

For the future it would be better to migrate to [Nettrine](https://github.com/nettrine) anyway.

And yes, for events I fully recommend use contributte/event-dispatcher.

**Comment by JakubBarta** [comment]
Very well, I'll look into it. Thanks!

**Comment by enumag** [comment]
Actually I think that the master branch of Kdyby/Doctrine already dropped the dependency. So it's all about finishing some other things necessary for Kdyby/Doctrine 4.0. I have long since forgotten the current state of things in that regard but the main discussion was [here](https://github.com/Kdyby/Doctrine/issues/238). It's not exactly necessary to finish all the ideas in this thread, we just need to put the package into some stable state.

**Comment by enumag** [comment]
Making Kdyby/Console optional is a must because the recommended way now is contributte/console (imo).

**Comment by enumag** [comment]
Optional Kdyby/Annotations would be nice too. See https://github.com/Kdyby/Doctrine/issues/268.
