### ISSUE TITLE
GetSubscribedEvents on partially initialized instance.

### ISSUE THREAD

**Issue by hrach** [Kdyby/Events#63]
getting the subscribed events is quite hacky, for example injections are not injected... so, it is impossible to do any logic in there. I see no added value in this, make it static, or create the instance properly, what do you think?

**Comment by hrach** [comment]
Well, maybe let me clear the need, then it may be more obvious. I have a neo4j services, which store some metadata (and updated them tgrouh evets). I have it also on my local machine, but not every developer should be forced to have it, since it's just small part of the app. So I would like to add listener somehow conditionaly. This was the first idea (the easiest): to let me inject my ParameterProvider, when I have option for it. 

What is the proper solution?

**Comment by fprochazka** [comment]
You might have a listener that is invoked on connection to database or application init, that adds another listener if needed. You can don't have to specify all events in the `getSubscribedEvents`, you may add them manually.

Might something like this help?

```php
class SomeListener implements Subsriber
{
    public function __construct(EventManager $evm)
    {
        // ...
    }

    public function getSubscribedEvents(...)
    {
        return ['Neo4js::onConnect'];
    }

    public function onConnect(...)
    {
        // ...
        $this->evm->addEventListener('Neo4js::onMetadataUpdate', [$this, 'onMetadataUpdate']);
    }

    public function onMetadataUpdate(..)
    {
        // ...
    }
```

Doctrine uses similar mechanism to add listener for `onClear` [in it's hydrator](https://github.com/doctrine/doctrine2/blob/52376929795d7537f725409c1150d1b76ecc32a0/lib/Doctrine/ORM/Internal/Hydration/AbstractHydrator.php#L122-L123). Because it doesn't have the lazy listeners natively and therefore it adds it only when it's needed.

But I'm not sure I've understood you properly. Možná to bude snadnější česky?

**Comment by hrach** [comment]
You understood it correcty. The problem is, the connection is needed only when the event occurs.

**Comment by hrach** [comment]
Well, I solved this by own extension. So, I don't need any features for doing this, but I would force the getSbscribedEvents to be static.

**Comment by fprochazka** [comment]
I don't consider this a problem. If you provide better solution that will not break BC, I shall consider it.

**Comment by hrach** [comment]
What? Why should I provide solution for something ,which isn't a problem :P
